Repository ravin-d-27/PyDeepFlow, pull requests merged in 2025-10, with the labels that each got.

#44 Added detailed docstrings for regularization.py and main.py
  pydeepflow/main.py
  pydeepflow/regularization.py
Labels: documentation, enhancement, Hacktoberfest

#50 feat: Add Adam and RMSprop optimizers and fix training loop
  pydeepflow/model.py
  pydeepflow/optimizers.py
  runner.py
  tests/test_model.py
Labels: enhancement, Hacktoberfest

#53 feat: Add evaluation metrics and learning curve plotting
  pydeepflow/gridSearch.py
  pydeepflow/metrics.py
  pydeepflow/model.py
  runner.py
  tests/test_metrics.py
  tests/test_model.py
Labels: enhancement, Hacktoberfest

#72 Fix Syntax Errors and Critical Import Bugs 🔴
  pydeepflow/__init__.py
  pydeepflow/model.py
  requirements.txt
  setup.py
Labels: bug, Hacktoberfest

#73 feat:added new regression metrics for evaluation
  README.md
  pydeepflow/metrics.py
  pydeepflow/model.py
  tests/test_metrics.py
Labels: enhancement, Hacktoberfest
